name: Publish to PyPI

on:
    workflow_dispatch:
    push:
        tags:
            - "v*"

permissions:
    contents: read

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install build backend
              run: python -m pip install --upgrade pip build

            - name: Build distribution
              run: python -m build

            - name: Publish to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  user: __token__
                  password: ${{ secrets.PYPI_API_TOKEN }}
